-- ১. টেবিল তৈরি (যদি আগে থেকে না থাকে)
create table if not exists daily_accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  report_date date not null,
  opening_balance numeric default 0,
  cash_received numeric default 0,
  handover_client numeric default 0,
  handover_bill numeric default 0,
  petty_cash numeric default 0,
  unique(user_id, report_date)
);

-- ২. বিস্তারিত ট্রানজেকশন রাখার টেবিল (নতুন)
create table if not exists transactions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  t_date date not null,
  t_type text not null,
  party_name text,
  amount numeric default 0
);

-- ৩. সিকিউরিটি অন করা (RLS)
alter table daily_accounts enable row level security;
alter table transactions enable row level security;

-- ৪. পলিসি তৈরি
create policy if not exists "Users can view own data" on daily_accounts for select using (auth.uid() = user_id);
create policy if not exists "Users can insert own data" on daily_accounts for insert with check (auth.uid() = user_id);
create policy if not exists "Users can update own data" on daily_accounts for update using (auth.uid() = user_id);

create policy if not exists "Users can view own transactions" on transactions for select using (auth.uid() = user_id);
create policy if not exists "Users can insert own transactions" on transactions for insert with check (auth.uid() = user_id);
create policy if not exists "Users can delete own transactions" on transactions for delete using (auth.uid() = user_id);
