-- ১. টেবিল তৈরি
create table daily_accounts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  report_date date not null,
  opening_balance numeric default 0,
  cash_received numeric default 0,
  handover_client numeric default 0,
  handover_bill numeric default 0,
  petty_cash numeric default 0,
  unique(user_id, report_date)
);

-- ২. সিকিউরিটি অন করা (RLS)
alter table daily_accounts enable row level security;

-- ৩. পলিসি তৈরি (যাতে একজন আরেকজনের ডাটা না দেখে)
create policy "Users can view own data" on daily_accounts for select using (auth.uid() = user_id);
create policy "Users can insert own data" on daily_accounts for insert with check (auth.uid() = user_id);
create policy "Users can update own data" on daily_accounts for update using (auth.uid() = user_id);
