-- Cash Counter History Table
create table if not exists cash_counter_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  count_date date not null,
  denomination_data jsonb not null,
  total_counted numeric default 0,
  expected_cash numeric default 0,
  difference numeric default 0,
  unique(user_id, count_date)
);

alter table cash_counter_history enable row level security;

drop policy if exists "Users can view own counter history" on cash_counter_history;
drop policy if exists "Users can insert own counter history" on cash_counter_history;
drop policy if exists "Users can update own counter history" on cash_counter_history;

create policy "Users can view own counter history" on cash_counter_history for select using (auth.uid() = user_id);
create policy "Users can insert own counter history" on cash_counter_history for insert with check (auth.uid() = user_id);
create policy "Users can update own counter history" on cash_counter_history for update using (auth.uid() = user_id);
