-- Expense Categories Table (Dynamic Category Management)
create table if not exists expense_categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  category_name text not null,
  icon text not null,
  is_default boolean default false,
  unique(user_id, category_name)
);

-- Index for faster queries
create index if not exists expense_categories_user_idx on expense_categories(user_id);

-- Row Level Security
alter table expense_categories enable row level security;

-- Policy: Users can manage their own categories
create policy "Users can manage own categories" on expense_categories
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Insert default categories for all users (run this once per user on first login)
-- This will be handled by JavaScript on first load
