-- Personal Expenses Table (আলাদা খরচ খাতা)
create table if not exists personal_expenses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users not null,
  e_date date not null,
  item_name text not null,
  category text,
  amount numeric default 0
);

-- Index for faster queries
create index if not exists personal_expenses_user_date_idx on personal_expenses(user_id, e_date desc);

-- Row Level Security
alter table personal_expenses enable row level security;

-- Policy: Users can only see their own expenses
create policy "Users can manage own expenses" on personal_expenses
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
